var express = require("express");
var app = express();

app.use(express.static(__dirname + '/public'));
const exphbs = require('express-handlebars');
app.engine('hbs', exphbs({
    layoutsDir: 'views',
    defaultLayout: 'layout',
    extname: '.hbs'
}));
app.set('view engine', 'hbs');
app.get("/goodlist",function (req,res) {
    var pagenumber= req.query.pageNumber;
    var vis= new Array();
    var totpage=7;
    for(var i=1;i<=totpage;++i){
        vis[i]=false;
    }
    vis[pagenumber]=true;
     var prepage= pagenumber;
     var nextpage = pagenumber;
     if(parseInt(prepage)-1>0){
         prepage=prepage-1;
     }
    if(parseInt(nextpage)+1<=totpage){
        nextpage=parseInt(nextpage)+1;
    }

    res.render("goodlist",{

        layout:false,
        prepage:prepage,
        nextpage:nextpage,
        onepieceInfoList:[
            {
            vis:vis[1],
                images1:[
                    {
                        src:"/static/images/image1_1.png"
                    },
                    {
                        src:"/static/images/image1_2.png"
                    },
                    {
                        src:"/static/images/image1_3.png"
                    },
                    {
                        src:"/static/images/image1_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image1_5.png"
                    },
                    {
                        src:"/static/images/image1_6.png"
                    },
                    {
                        src:"/static/images/image1_7.png"
                    },
                    {
                        src:"/static/images/image1_8.png"
                    },
                ],
            },
            {
                vis:vis[2],
                images1:[
                    {
                        src:"/static/images/image2_1.png"
                    },
                    {
                        src:"/static/images/image2_2.png"
                    },
                    {
                        src:"/static/images/image2_3.png"
                    },
                    {
                        src:"/static/images/image2_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image2_5.png"
                    },
                    {
                        src:"/static/images/image2_6.png"
                    },
                    {
                        src:"/static/images/image2_7.png"
                    },
                    {
                        src:"/static/images/image2_8.png"
                    },
                ],
            },
            {
                vis:vis[3],
                images1:[
                    {
                        src:"/static/images/image3_1.png"
                    },
                    {
                        src:"/static/images/image3_2.png"
                    },
                    {
                        src:"/static/images/image3_3.png"
                    },
                    {
                        src:"/static/images/image3_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image3_5.png"
                    },
                    {
                        src:"/static/images/image3_6.png"
                    },
                    {
                        src:"/static/images/image3_7.png"
                    },
                    {
                        src:"/static/images/image3_8.png"
                    },
                ],
            },
            {
                vis:vis[4],
                images1:[
                    {
                        src:"/static/images/image4_1.png"
                    },
                    {
                        src:"/static/images/image4_2.png"
                    },
                    {
                        src:"/static/images/image4_3.png"
                    },
                    {
                        src:"/static/images/image4_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image4_5.png"
                    },
                    {
                        src:"/static/images/image4_6.png"
                    },
                    {
                        src:"/static/images/image4_7.png"
                    },
                    {
                        src:"/static/images/image4_8.png"
                    },
                ],
            },
            {
                vis:vis[5],
                images1:[
                    {
                        src:"/static/images/image5_1.png"
                    },
                    {
                        src:"/static/images/image5_2.png"
                    },
                    {
                        src:"/static/images/image5_3.png"
                    },
                    {
                        src:"/static/images/image5_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image5_5.png"
                    },
                    {
                        src:"/static/images/image5_6.png"
                    },
                    {
                        src:"/static/images/image5_7.png"
                    },
                    {
                        src:"/static/images/image5_8.png"
                    },
                ],
            },
            {
                vis:vis[6],
                images1:[
                    {
                        src:"/static/images/image6_1.png"
                    },
                    {
                        src:"/static/images/image6_2.png"
                    },
                    {
                        src:"/static/images/image6_3.png"
                    },
                    {
                        src:"/static/images/image6_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image6_5.png"
                    },
                    {
                        src:"/static/images/image6_6.png"
                    },
                    {
                        src:"/static/images/image6_7.png"
                    },
                    {
                        src:"/static/images/image6_8.png"
                    },
                ],
            },
            {
                vis:vis[7],
                images1:[
                    {
                        src:"/static/images/image7_1.png"
                    },
                    {
                        src:"/static/images/image7_2.png"
                    },
                    {
                        src:"/static/images/image7_3.png"
                    },
                    {
                        src:"/static/images/image7_4.png"
                    },
                ],
                images2:[
                    {
                        src:"/static/images/image7_5.png"
                    },
                    {
                        src:"/static/images/image7_6.png"
                    },
                    {
                        src:"/static/images/image7_7.png"
                    },
                    {
                        src:"/static/images/image7_8.png"
                    },
                ],
            }
        ]
    });
});
app.listen(1227);