var datas = {
    "products":[
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":0},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":1},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":2},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":3},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":4},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":5},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":6},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":7},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":8},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":9},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":10},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":11},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":12},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":13},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":14},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":15},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":16},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":17},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":18},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":19},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":20},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":21},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":22},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":23},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":24},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":25},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":26},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":27},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":28},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":29},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":30},
      { "image": "/images/2.jpg", "name": "小黄人玩偶" ,"id":31},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":32},
      { "image": "/images/1.jpg", "name": "小黄人音响" ,"id":33},
    ]
  };
  module.exports=datas;