var datas = {
    "products":[
      { "image": "/images/1.jpg", "name": "耳机1" ,"id":0},
      { "image": "/images/2.jpg", "name": "耳机2" ,"id":1},
      { "image": "/images/3.jpg", "name": "耳机3" ,"id":2},
      { "image": "/images/4.jpg", "name": "耳机4" ,"id":3},
      { "image": "/images/5.jpg", "name": "耳机5" ,"id":4},
      { "image": "/images/1.jpg", "name": "耳机6" ,"id":5},
      { "image": "/images/2.jpg", "name": "耳机7" ,"id":6},
      { "image": "/images/3.jpg", "name": "耳机8" ,"id":7},
      { "image": "/images/4.jpg", "name": "耳机9" ,"id":8},
      { "image": "/images/5.jpg", "name": "耳机10" ,"id":9},
      { "image": "/images/1.jpg", "name": "耳机11" ,"id":10},
      { "image": "/images/2.jpg", "name": "耳机12" ,"id":11},
      { "image": "/images/3.jpg", "name": "耳机13" ,"id":12},
      { "image": "/images/4.jpg", "name": "耳机14" ,"id":13},
      { "image": "/images/5.jpg", "name": "耳机15" ,"id":14},
      { "image": "/images/1.jpg", "name": "耳机16" ,"id":15},
      { "image": "/images/2.jpg", "name": "耳机17" ,"id":16},
      { "image": "/images/3.jpg", "name": "耳机18" ,"id":17},
      { "image": "/images/4.jpg", "name": "耳机19" ,"id":18},
      { "image": "/images/5.jpg", "name": "耳机20" ,"id":19},
      { "image": "/images/1.jpg", "name": "耳机21" ,"id":20},
      { "image": "/images/2.jpg", "name": "耳机22" ,"id":21},
      { "image": "/images/3.jpg", "name": "耳机23" ,"id":22},
      { "image": "/images/4.jpg", "name": "耳机24" ,"id":23},
      { "image": "/images/5.jpg", "name": "耳机25" ,"id":24},
      { "image": "/images/1.jpg", "name": "耳机26" ,"id":25},
      { "image": "/images/2.jpg", "name": "耳机27" ,"id":26},
      { "image": "/images/3.jpg", "name": "耳机28" ,"id":27},
      { "image": "/images/4.jpg", "name": "耳机29" ,"id":28},
      { "image": "/images/5.jpg", "name": "耳机30" ,"id":29},
      { "image": "/images/1.jpg", "name": "耳机31" ,"id":30},
      { "image": "/images/2.jpg", "name": "耳机32" ,"id":31},
      { "image": "/images/3.jpg", "name": "耳机33" ,"id":32},
      { "image": "/images/4.jpg", "name": "耳机34" ,"id":33},
    ]
  };
  module.exports=datas;